PARENT_CFG_NAME: ""

GPUS: [7]

NUM_ITER_PER_EP: -1
EVAL_EP: 100

RESUME: true
LOG_INTERVAL: 20
RECORD_INTERVAL: 20

SAVE_EP: 100
SAVE_LATEST_EP: 5

MODULE:
  NAME: resnet101
  USE_LAYER: 4

TEST:
  BATCH_SIZE: 1
  DATASET: dataset
  EPOCH: -1
TRAIN:
  BATCH_SIZE: 4
  DATASET: dataset
  EPOCH: 10000
  LR: 0.001
  NUM_WORKERS: 8
